"""protofiles -> ROS2 `.msg` / `.srv` interface definitions.

Compiles the target protos to a FileDescriptorSet with the protoc bundled in
grpc_tools (no system protoc needed, same as the producer codegen does), then
renders one `.msg` per message and one `.srv` per rpc method.

Meant to be driven from an interface package's CMakeLists at *configure* time,
so `colcon build` is the whole workflow -- there is no separate generate step to
forget and no way to build against a stale interface. Only the ament plumbing
(package.xml, CMakeLists.txt) is committed; msg/ and srv/ are generated.

The mapping is deliberately narrow: anything without a faithful ROS2 equivalent
raises Ros2GenError instead of emitting something misleading. See
render_interfaces() for the full list, both directions.
"""

from __future__ import annotations

import fnmatch
import re
import tempfile
from dataclasses import dataclass, field
from pathlib import Path

from google.protobuf import descriptor_pb2, descriptor_pool, message_factory

GENERATED_MARKER = "Generated by proto4webrtc_codegen.ros2"

# proto scalar type -> ROS2 interface primitive.
# Note the deliberate widenings: proto's zigzag/fixed encodings are wire
# details, not value ranges, so they collapse onto the plain ROS integer of the
# same signedness and width.
_SCALAR = {
    descriptor_pb2.FieldDescriptorProto.TYPE_DOUBLE: "float64",
    descriptor_pb2.FieldDescriptorProto.TYPE_FLOAT: "float32",
    descriptor_pb2.FieldDescriptorProto.TYPE_INT64: "int64",
    descriptor_pb2.FieldDescriptorProto.TYPE_UINT64: "uint64",
    descriptor_pb2.FieldDescriptorProto.TYPE_INT32: "int32",
    descriptor_pb2.FieldDescriptorProto.TYPE_FIXED64: "uint64",
    descriptor_pb2.FieldDescriptorProto.TYPE_FIXED32: "uint32",
    descriptor_pb2.FieldDescriptorProto.TYPE_BOOL: "bool",
    descriptor_pb2.FieldDescriptorProto.TYPE_STRING: "string",
    descriptor_pb2.FieldDescriptorProto.TYPE_UINT32: "uint32",
    descriptor_pb2.FieldDescriptorProto.TYPE_SFIXED32: "int32",
    descriptor_pb2.FieldDescriptorProto.TYPE_SFIXED64: "int64",
    descriptor_pb2.FieldDescriptorProto.TYPE_SINT32: "int32",
    descriptor_pb2.FieldDescriptorProto.TYPE_SINT64: "int64",
}

_BYTES = descriptor_pb2.FieldDescriptorProto.TYPE_BYTES
_MESSAGE = descriptor_pb2.FieldDescriptorProto.TYPE_MESSAGE
_ENUM = descriptor_pb2.FieldDescriptorProto.TYPE_ENUM
_LABEL_REPEATED = descriptor_pb2.FieldDescriptorProto.LABEL_REPEATED

MEDIA_STREAM_EXT = "proto4webrtc.media_stream"

# ROS2 field names: lowercase, underscore-separated, no leading/trailing or
# doubled underscores. protoc already rejects most of what would break this, but
# `myField` is legal proto and illegal here.
_ROS_FIELD_RE = re.compile(r"^[a-z](?:_?[a-z0-9])*$")

# Interface (file) names are CamelCase; constants are UPPER_SNAKE. Both are
# rosidl rules rather than ours -- catching them here turns an opaque
# mid-`colcon build` failure into an error naming the .proto to edit.
_ROS_TYPE_RE = re.compile(r"^[A-Z][A-Za-z0-9]*$")
_ROS_CONST_RE = re.compile(r"^[A-Z](?:_?[A-Z0-9])*$")

# rosidl generates C++ and Python from every field name, so a field that is a
# keyword in either language builds a package that will not compile. protoc
# accepts all of them.
_RESERVED_FIELD_NAMES = frozenset(
    {
        # C++
        "alignas", "alignof", "and", "asm", "auto", "bool", "break", "case",
        "catch", "char", "class", "const", "constexpr", "continue", "decltype",
        "default", "delete", "do", "double", "dynamic_cast", "else", "enum",
        "explicit", "export", "extern", "false", "float", "for", "friend",
        "goto", "if", "inline", "int", "long", "mutable", "namespace", "new",
        "noexcept", "not", "nullptr", "operator", "or", "private", "protected",
        "public", "register", "return", "short", "signed", "sizeof", "static",
        "static_cast", "struct", "switch", "template", "this", "throw", "true",
        "try", "typedef", "typeid", "typename", "union", "unsigned", "using",
        "virtual", "void", "volatile", "while", "xor",
        # Python-only additions
        "and_", "as", "assert", "async", "await", "def", "del", "elif",
        "except", "finally", "from", "global", "import", "in", "is", "lambda",
        "nonlocal", "pass", "raise", "with", "yield",
    }
)

OPTIONS_PROTO = "proto4webrtc/options.proto"


class Ros2GenError(RuntimeError):
    """A proto construct that has no faithful ROS2 interface equivalent."""


@dataclass
class _Field:
    ros_type: str  # e.g. "float64", "uint8[]", "MissionWaypoint"
    name: str
    # Set when the field was a proto enum: the values become a constants block.
    enum: tuple[str, tuple[tuple[str, int], ...]] | None = None


@dataclass
class _Block:
    """One rendered field block: the constants it needs, then its fields."""

    fields: list[_Field] = field(default_factory=list)


@dataclass
class _Interface:
    rel_path: str  # e.g. "msg/Thrusters.msg" or "srv/Ping.srv"
    source: str  # originating .proto path, for the generated header
    blocks: list[_Block]  # one block for a msg; request then response for a srv


@dataclass
class _MsgRec:
    """A proto message that has (or would have) a ROS2 counterpart."""

    desc: descriptor_pb2.DescriptorProto
    fq: str  # ".rov.streams.PointCloud"
    ros_name: str  # "PointCloud"; nested types flatten (MissionWaypoint)
    file: str  # "rov/streams/pointcloud.proto"


# ---------------------------------------------------------------------------
# public entry point
# ---------------------------------------------------------------------------


def generate_interfaces(
    proto_dirs,
    out_dir,
    include=None,
    services: bool = True,
    srv_prefix_service: bool = False,
) -> list[str]:
    """Render `.msg`/`.srv` files under out_dir; return their relative paths.

    proto_dirs: one dir or a list of dirs; each is a protoc include root.
    out_dir: the ament interface package's directory. `msg/` and `srv/` inside
        it are managed here -- files this generated before but no longer would
        are deleted, and only those (the header marker is what identifies them),
        so hand-written interfaces beside them survive.
    include: optional list of globs (relative to the roots, e.g.
        "telemetry/*.proto"); when given, only matching files become interfaces.
        Non-matching files stay importable, so this is how proto packages no ROS
        node consumes are kept out of the interface package.
    services: render `.srv` files from rpc methods. False emits messages only.
    srv_prefix_service: name srv files `<Service><Method>.srv` instead of
        `<Method>.srv`. Needed when two services share a method name.

    Unchanged files are not rewritten, so an unchanged proto costs no rosidl
    rebuild.
    """
    if isinstance(proto_dirs, (str, Path)):
        proto_dirs = [proto_dirs]
    roots = [Path(d).resolve() for d in proto_dirs]
    for root in roots:
        if not root.is_dir():
            raise Ros2GenError(f"proto root does not exist: {root}")
    out_dir = Path(out_dir).resolve()

    targets = _find_targets(roots, include)
    if not targets:
        raise Ros2GenError(
            f"no .proto files matched under {[str(r) for r in roots]}"
            + (f" with include={include}" if include else "")
        )

    fdset = _compile(roots, targets)
    interfaces = render_interfaces(
        fdset,
        target_names=set(targets),
        services=services,
        srv_prefix_service=srv_prefix_service,
    )
    return _write(out_dir, interfaces)


def render_interfaces(
    fdset: descriptor_pb2.FileDescriptorSet,
    target_names: set[str],
    services: bool = True,
    srv_prefix_service: bool = False,
) -> list[_Interface]:
    """Descriptors -> interface records. The whole mapping, in one place.

    - message -> `msg/<Name>.msg`; nested messages flatten into the parent's
      name (`Mission.Waypoint` -> `MissionWaypoint`), because a ROS2 interface
      package is one flat namespace.
    - `rpc M(MRequest) returns (MResponse)` -> `srv/<M>.srv`, request fields
      inlined above `---`, response fields below. A message that exists only to
      be a payload gets no `.msg` of its own -- see _Registry.is_payload_only()
      for exactly when that applies.
    - proto enum -> an `int32` field plus a constants block, repeated in every
      interface file that uses the enum. That is how ROS2 conventionally
      expresses an enumeration; the value numbers are proto's, unchanged.
    - `bytes` -> `uint8[]`.
    - declaration-only `(proto4webrtc.media_stream)` messages are skipped: RTP
      frames never travel as protobuf, so there is nothing to put in a msg.

    Rejected rather than approximated: `oneof` (loses the exactly-one-set
    invariant), `map<>`, `repeated bytes` (a nested array, inexpressible),
    streaming rpcs, field names that aren't lower_snake_case, references into
    files the target set leaves out, and flattened name collisions.
    """
    registry = _Registry(fdset, target_names)
    out: list[_Interface] = []

    for rec in registry.messages:
        if registry.is_payload_only(rec.fq):
            continue  # rendered inside its .srv instead
        name = _check_name(rec.ros_name, "msg", rec.file, rec.fq.lstrip("."))
        out.append(
            _Interface(
                rel_path=f"msg/{name}.msg",
                source=rec.file,
                blocks=[_block(rec, registry)],
            )
        )

    if services:
        for file in fdset.file:
            if file.name not in target_names:
                continue
            for service in file.service:
                for method in service.method:
                    name = _check_name(
                        f"{service.name}{method.name}"
                        if srv_prefix_service
                        else method.name,
                        "srv",
                        file.name,
                        f"{service.name}.{method.name}",
                    )
                    out.append(
                        _Interface(
                            rel_path=f"srv/{name}.srv",
                            source=file.name,
                            blocks=[
                                _block(registry.by_fq[method.input_type], registry),
                                _block(registry.by_fq[method.output_type], registry),
                            ],
                        )
                    )

    _check_unique(out)
    return sorted(out, key=lambda i: i.rel_path)


# ---------------------------------------------------------------------------
# descriptors
# ---------------------------------------------------------------------------


def _find_targets(roots: list[Path], include) -> list[str]:
    """Target proto paths, relative to their root."""
    patterns = None
    if include is not None:
        patterns = [include] if isinstance(include, str) else list(include)

    out: list[str] = []
    for root in roots:
        for path in sorted(root.rglob("*.proto")):
            rel = path.relative_to(root).as_posix()
            if rel == OPTIONS_PROTO:
                continue  # the annotations themselves are never an interface
            if patterns and not any(fnmatch.fnmatch(rel, pat) for pat in patterns):
                continue
            out.append(rel)
    if len(set(out)) != len(out):
        raise Ros2GenError(f"duplicate proto paths across roots {roots}")
    return out


def _compile(roots: list[Path], targets: list[str]) -> descriptor_pb2.FileDescriptorSet:
    """Run protoc, return the parsed FileDescriptorSet."""
    # Imported lazily: grpc_tools is codegen-only, absent from runtime images.
    from grpc_tools import protoc

    from proto4webrtc_codegen.driver import (
        _well_known_include,
        bundled_options_include,
    )

    # The bundled proto4webrtc/options.proto goes on the include path (never as
    # a target), which is what lets the stream annotations resolve without
    # vendoring a second copy into the consumer's tree.
    includes = [str(r) for r in roots] + [
        bundled_options_include(),
        _well_known_include(),
    ]

    with tempfile.TemporaryDirectory() as tmp:
        desc = Path(tmp) / "descriptors.binpb"
        argv = (
            ["protoc"]
            + [f"-I{i}" for i in includes]
            + [f"--descriptor_set_out={desc}", "--include_imports"]
            + list(targets)
        )
        if protoc.main(argv) != 0:
            raise Ros2GenError("protoc failed; see the errors above")
        fdset = descriptor_pb2.FileDescriptorSet()
        fdset.ParseFromString(desc.read_bytes())
    return fdset


class _Registry:
    """What every fully-qualified proto name becomes in the ROS2 package."""

    def __init__(self, fdset: descriptor_pb2.FileDescriptorSet, target_names: set[str]):
        self.messages: list[_MsgRec] = []
        self.by_fq: dict[str, _MsgRec] = {}
        self.map_entries: set[str] = set()
        self.enums: dict[str, tuple[tuple[str, int], ...]] = {}
        self.rpc_messages: dict[str, str] = {}  # fq -> "Service.Method" using it
        self.referenced: set[str] = set()  # fq of every message used as a field type
        self._is_media_stream = _media_stream_check(fdset)

        for file in fdset.file:
            if file.name not in target_names:
                continue  # a resolved import (proto4webrtc/options.proto, wkt, ...)
            scope = f".{file.package}" if file.package else ""
            for enum in file.enum_type:
                self.enums[f"{scope}.{enum.name}"] = tuple(
                    (v.name, v.number) for v in enum.value
                )
            for msg in file.message_type:
                self._walk(msg, scope, "", file.name)

        for rec in self.messages:
            for f in rec.desc.field:
                if f.type == _MESSAGE:
                    self.referenced.add(f.type_name)

        for file in fdset.file:
            if file.name not in target_names:
                continue
            for service in file.service:
                for method in service.method:
                    self._register_rpc(file, service, method)

    def is_payload_only(self, fq: str) -> bool:
        """True for a message that exists *only* to be an rpc payload.

        Those are rendered inside their `.srv` and get no `.msg` of their own: a
        `GetMissionRequest {}` has no meaning as a topic type. Three conditions,
        all required, so the skip never surprises:

        - it is some rpc's request or response type,
        - no other message uses it as a field type (a response that is the
          resource itself -- `rpc GetMission(...) returns (Mission)` alongside a
          `Mission mission` field -- keeps its `.msg`; something needs the type),
        - and it looks like a payload: `*Request`/`*Response` by name, or empty.
          A hand-named message with real fields (`rpc Poke(Status) returns
          (Status)`) is a type in its own right and keeps its `.msg`.
        """
        if fq not in self.rpc_messages or fq in self.referenced:
            return False
        rec = self.by_fq[fq]
        return rec.ros_name.endswith(("Request", "Response")) or not rec.desc.field

    def _walk(self, msg, scope: str, prefix: str, file_name: str) -> None:
        fq = f"{scope}.{msg.name}"
        if msg.options.map_entry:
            self.map_entries.add(fq)  # synthetic entry type for a map<> field
            return
        for enum in msg.enum_type:
            self.enums[f"{fq}.{enum.name}"] = tuple(
                (v.name, v.number) for v in enum.value
            )
        # One flat ROS2 namespace, so a nested message's name is its nested path
        # with the dots removed: pkg.Mission.Waypoint -> MissionWaypoint.
        ros_name = prefix + msg.name
        if not self._is_media_stream(msg):
            rec = _MsgRec(desc=msg, fq=fq, ros_name=ros_name, file=file_name)
            self.messages.append(rec)
            self.by_fq[fq] = rec
        for nested in msg.nested_type:
            self._walk(nested, fq, ros_name, file_name)

    def _register_rpc(self, file, service, method) -> None:
        where = f"{service.name}.{method.name}"
        if method.client_streaming or method.server_streaming:
            raise Ros2GenError(
                f"{file.name}: {where} is streaming, and a ROS2 service is unary. "
                f"Carry the stream on a topic (a plain message) instead."
            )
        for kind, fq in (
            ("request", method.input_type),
            ("response", method.output_type),
        ):
            if fq not in self.by_fq:
                raise Ros2GenError(
                    f"{file.name}: {where} {kind} type {fq} is not in the target "
                    f"set (its file is left out by include=, or it is a "
                    f"well-known type). Add its file, or drop the rpc."
                )
            self.rpc_messages[fq] = where


def _media_stream_check(fdset: descriptor_pb2.FileDescriptorSet):
    """Return is_media_stream(DescriptorProto) -> bool.

    The proto4webrtc options are extensions of google.protobuf.MessageOptions
    that descriptor_pb2 doesn't know, so protoc parks them in the options'
    unknown fields. Re-parsing them against a pool built from the descriptor set
    (which contains proto4webrtc/options.proto -- protoc ran with
    --include_imports) is what surfaces them; the same trick extract.py uses.

    Protos that don't import the options at all are the ordinary case for this
    module -- a ROS user's interface protos need no proto4webrtc annotation -- so
    a set without options.proto is not an error: nothing is a media stream.
    """
    pool = descriptor_pool.DescriptorPool()
    for fdp in fdset.file:  # --include_imports output is dependency-ordered
        pool.Add(fdp)
    try:
        media_ext = pool.FindExtensionByName(MEDIA_STREAM_EXT)
    except KeyError:
        return lambda msg: False
    options_cls = message_factory.GetMessageClass(
        pool.FindMessageTypeByName("google.protobuf.MessageOptions")
    )

    def is_media_stream(msg: descriptor_pb2.DescriptorProto) -> bool:
        opts = options_cls()
        opts.ParseFromString(msg.options.SerializeToString())
        return opts.HasExtension(media_ext)

    return is_media_stream


# ---------------------------------------------------------------------------
# rendering
# ---------------------------------------------------------------------------


def _block(rec: _MsgRec, registry: _Registry) -> _Block:
    if rec.desc.oneof_decl:
        # A faithful translation needs a discriminator convention, and silently
        # flattening a oneof into always-present fields loses the invariant that
        # exactly one is set. Refuse rather than generate something misleading.
        raise Ros2GenError(
            f"{rec.file}:{rec.ros_name}: `oneof` has no ROS2 interface "
            f"equivalent. Restructure the message, or leave this file out of "
            f"include=."
        )
    return _Block(fields=[_field(f, rec, registry) for f in rec.desc.field])


def _field(f, rec: _MsgRec, registry: _Registry) -> _Field:
    where = f"{rec.file}:{rec.ros_name}.{f.name}"
    if not _ROS_FIELD_RE.match(f.name):
        raise Ros2GenError(
            f"{where}: not a valid ROS2 field name (must be lower_snake_case); "
            f"rename it in the .proto"
        )
    if f.name in _RESERVED_FIELD_NAMES:
        raise Ros2GenError(
            f"{where}: `{f.name}` is a C++/Python keyword, so rosidl would "
            f"generate code that does not compile; rename it in the .proto"
        )
    repeated = f.label == _LABEL_REPEATED
    suffix = "[]" if repeated else ""

    if f.type == _MESSAGE:
        if f.type_name in registry.map_entries:
            raise Ros2GenError(
                f"{where}: `map<>` has no ROS2 interface equivalent. Use a "
                f"repeated key/value message instead."
            )
        if f.type_name not in registry.by_fq:
            raise Ros2GenError(
                f"{where}: {f.type_name} is not in the target set (its file is "
                f"left out by include=, it is a well-known type, or it is a "
                f"declaration-only media_stream message). Add its file, or drop "
                f"the field."
            )
        return _Field(registry.by_fq[f.type_name].ros_name + suffix, f.name)

    if f.type == _ENUM:
        if f.type_name not in registry.enums:
            raise Ros2GenError(
                f"{where}: enum {f.type_name} is not in the target set; add its "
                f"file to include=."
            )
        values = registry.enums[f.type_name]
        for value_name, _number in values:
            if not _ROS_CONST_RE.match(value_name):
                raise Ros2GenError(
                    f"{where}: enum value {f.type_name}.{value_name} is not a "
                    f"valid ROS2 constant name (must be UPPER_SNAKE_CASE); "
                    f"rename it in the .proto"
                )
        # The field is an int32; the values become a constants block above it.
        return _Field("int32" + suffix, f.name, enum=(f.type_name, values))

    if f.type == _BYTES:
        if repeated:
            raise Ros2GenError(
                f"{where}: `repeated bytes` would need a nested array, which a "
                f"ROS2 interface cannot express. Wrap it in a message."
            )
        return _Field("uint8[]", f.name)

    try:
        return _Field(_SCALAR[f.type] + suffix, f.name)
    except KeyError:  # pragma: no cover - protoc emits nothing else
        raise Ros2GenError(f"{where}: unsupported proto type {f.type}") from None


def _check_name(name: str, kind: str, source: str, origin: str) -> str:
    """Validate a generated interface name; return it."""
    if not _ROS_TYPE_RE.match(name):
        raise Ros2GenError(
            f"{source}: {origin} would become {kind}/{name}, which is not a "
            f"valid ROS2 interface name (must be CamelCase); rename it in the "
            f".proto"
        )
    return name


def _check_unique(interfaces: list[_Interface]) -> None:
    seen: dict[str, str] = {}
    for i in interfaces:
        if i.rel_path in seen:
            raise Ros2GenError(
                f"duplicate interface {i.rel_path}: from both {seen[i.rel_path]} "
                f"and {i.source}. All proto packages flatten into one ROS2 "
                f"interface package, so the names must be globally unique -- "
                f"rename, or pass --srv-prefix-service for colliding rpcs."
            )
        seen[i.rel_path] = i.source


def _render(interface: _Interface) -> str:
    lines = [
        f"# {GENERATED_MARKER} from {interface.source}. DO NOT EDIT.",
        "#",
        "# Edit the .proto instead; `colcon build` regenerates this directory.",
    ]
    for n, block in enumerate(interface.blocks):
        if n:
            lines.append("---")
        emitted: set[str] = set()
        for f in block.fields:
            if not f.enum or f.enum[0] in emitted:
                continue
            emitted.add(f.enum[0])
            lines.append("")
            lines += [f"int32 {name}={value}" for name, value in f.enum[1]]
        if block.fields:
            lines.append("")
        lines += [f"{f.ros_type} {f.name}" for f in block.fields]
    return "\n".join(lines) + "\n"


def _write(out_dir: Path, interfaces: list[_Interface]) -> list[str]:
    written: set[Path] = set()
    for interface in interfaces:
        path = out_dir / interface.rel_path
        path.parent.mkdir(parents=True, exist_ok=True)
        content = _render(interface)
        written.add(path)
        # Written only on change, so an unchanged proto costs no rosidl rebuild.
        if not path.exists() or path.read_text() != content:
            path.write_text(content)
    # Stale files are removed rather than left behind: an interface deleted from
    # the protos would otherwise linger as a .msg that CMake's glob still picks
    # up and builds. Only our own output is touched -- the marker proves it.
    for sub, pattern in (("msg", "*.msg"), ("srv", "*.srv")):
        directory = out_dir / sub
        if not directory.is_dir():
            continue
        for existing in sorted(directory.glob(pattern)):
            if existing not in written and GENERATED_MARKER in existing.read_text():
                existing.unlink()
    return [i.rel_path for i in interfaces]
