"""protoc plugin entry point: protoc-gen-proto4webrtc_python.

Standard protoc plugin protocol — CodeGeneratorRequest on stdin,
CodeGeneratorResponse on stdout. Usable directly:

    protoc -I proto \\
        --python_out=out --proto4webrtc_python_out=out \\
        example/streams.proto

or from buf.gen.yaml (use `strategy: all`: the plugin aggregates every
stream into one proto4webrtc_gen/producers.py, so it must see all files in a
single invocation).
"""

import sys

from google.protobuf import descriptor_pb2
from google.protobuf.compiler import plugin_pb2

from proto4webrtc_codegen.extract import extract_streams
from proto4webrtc_codegen.render_python import render_producers

# Relative import so the same content works whatever the generated package
# is named (generate()'s gen_package option).
INIT_CONTENT = (
    '"""Generated by proto4webrtc. Do not edit."""\n'
    "from .producers import *  # noqa: F401,F403\n"
)


def run(request: plugin_pb2.CodeGeneratorRequest) -> plugin_pb2.CodeGeneratorResponse:
    response = plugin_pb2.CodeGeneratorResponse()
    response.supported_features = (
        plugin_pb2.CodeGeneratorResponse.FEATURE_PROTO3_OPTIONAL
    )
    try:
        fdset = descriptor_pb2.FileDescriptorSet(file=request.proto_file)
        data_streams, media_streams, rpc_services = extract_streams(
            fdset, set(request.file_to_generate)
        )
        producers = response.file.add()
        producers.name = "proto4webrtc_gen/producers.py"
        producers.content = render_producers(
            data_streams, media_streams, rpc_services
        )
        init = response.file.add()
        init.name = "proto4webrtc_gen/__init__.py"
        init.content = INIT_CONTENT
    except Exception as exc:  # report through the plugin protocol, not stderr
        response.ClearField("file")
        response.error = str(exc)
    return response


def main():
    request = plugin_pb2.CodeGeneratorRequest.FromString(sys.stdin.buffer.read())
    sys.stdout.buffer.write(run(request).SerializeToString())


if __name__ == "__main__":
    main()
