# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto4webrtc/options.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'proto4webrtc/options.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1aproto4webrtc/options.proto\x12\x0cproto4webrtc\x1a google/protobuf/descriptor.proto\"\xae\x01\n\x11\x44\x61taStreamOptions\x12\r\n\x05label\x18\x01 \x01(\t\x12(\n\x08\x64\x65livery\x18\x02 \x01(\x0e\x32\x16.proto4webrtc.Delivery\x12\x30\n\x0c\x62\x61\x63kpressure\x18\x03 \x01(\x0e\x32\x1a.proto4webrtc.Backpressure\x12\x1b\n\x13max_buffered_factor\x18\x04 \x01(\r\x12\x11\n\tprotected\x18\x05 \x01(\x08\"\x8c\x01\n\x12MediaStreamOptions\x12\r\n\x05label\x18\x01 \x01(\t\x12%\n\x04kind\x18\x02 \x01(\x0e\x32\x17.proto4webrtc.MediaKind\x12-\n\x0bvideo_codec\x18\x03 \x01(\x0e\x32\x18.proto4webrtc.VideoCodec\x12\x11\n\tprotected\x18\x04 \x01(\x08\"\"\n\x11RpcServiceOptions\x12\r\n\x05label\x18\x01 \x01(\t*J\n\x08\x44\x65livery\x12\x18\n\x14\x44\x45LIVERY_UNSPECIFIED\x10\x00\x12\x14\n\x10RELIABLE_ORDERED\x10\x01\x12\x0e\n\nUNRELIABLE\x10\x02*R\n\x0c\x42\x61\x63kpressure\x12\x1c\n\x18\x42\x41\x43KPRESSURE_UNSPECIFIED\x10\x00\x12\x0e\n\nBUFFER_ALL\x10\x01\x12\x14\n\x10\x44ROP_IF_BUFFERED\x10\x02*=\n\tMediaKind\x12\x1a\n\x16MEDIA_KIND_UNSPECIFIED\x10\x00\x12\t\n\x05VIDEO\x10\x01\x12\t\n\x05\x41UDIO\x10\x02*E\n\nVideoCodec\x12\x1b\n\x17VIDEO_CODEC_UNSPECIFIED\x10\x00\x12\x07\n\x03VP8\x10\x01\x12\x07\n\x03VP9\x10\x02\x12\x08\n\x04H264\x10\x03*6\n\x04Role\x12\x0e\n\nROLE_ROBOT\x10\x00\x12\x0e\n\nROLE_GUEST\x10\x01\x12\x0e\n\nROLE_ADMIN\x10\x02:W\n\x0b\x64\x61ta_stream\x12\x1f.google.protobuf.MessageOptions\x18\xd0\x86\x03 \x01(\x0b\x32\x1f.proto4webrtc.DataStreamOptions:Y\n\x0cmedia_stream\x12\x1f.google.protobuf.MessageOptions\x18\xd1\x86\x03 \x01(\x0b\x32 .proto4webrtc.MediaStreamOptions:W\n\x0brpc_service\x12\x1f.google.protobuf.ServiceOptions\x18\xd0\x86\x03 \x01(\x0b\x32\x1f.proto4webrtc.RpcServiceOptions:3\n\tprotected\x12\x1e.google.protobuf.MethodOptions\x18\xd0\x86\x03 \x01(\x08\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto4webrtc.options_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DELIVERY']._serialized_start=434
  _globals['_DELIVERY']._serialized_end=508
  _globals['_BACKPRESSURE']._serialized_start=510
  _globals['_BACKPRESSURE']._serialized_end=592
  _globals['_MEDIAKIND']._serialized_start=594
  _globals['_MEDIAKIND']._serialized_end=655
  _globals['_VIDEOCODEC']._serialized_start=657
  _globals['_VIDEOCODEC']._serialized_end=726
  _globals['_ROLE']._serialized_start=728
  _globals['_ROLE']._serialized_end=782
  _globals['_DATASTREAMOPTIONS']._serialized_start=79
  _globals['_DATASTREAMOPTIONS']._serialized_end=253
  _globals['_MEDIASTREAMOPTIONS']._serialized_start=256
  _globals['_MEDIASTREAMOPTIONS']._serialized_end=396
  _globals['_RPCSERVICEOPTIONS']._serialized_start=398
  _globals['_RPCSERVICEOPTIONS']._serialized_end=432
# @@protoc_insertion_point(module_scope)
